version: "3.9"

services:
  artemis:
    image: vromero/activemq-artemis
    container_name: artemis
    ports:
      - "8161:8161"  # Web Console
      - "5672:5672"  # AMQP
      - "61616:61616"  # OpenWire
      - "61613:61613"  # STOMP
      - "61614:61614"  # MQTT
      - "5671:5671"  # AMQP over SSL
    environment:
      ENABLE_JMX: "true"
      ARTEMIS_USERNAME: "admin"
      ARTEMIS_PASSWORD: "admin"

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "8162:8161"  # Web Console
      - "61617:61616"  # OpenWire

  sftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - 2222:22
    environment:
      - SFTP_USERS=user:pass:::upload

  sftp2:
    image: atmoz/sftp
    container_name: sftp_2
    ports:
      - 2223:22
    environment:
      - SFTP_USERS=user:pass:::upload
